// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: log.proto

package log

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClient interface {
	UploadLogStream(ctx context.Context, opts ...grpc.CallOption) (Log_UploadLogStreamClient, error)
	UploadLogStatus(ctx context.Context, in *UploadLogStatus_Request, opts ...grpc.CallOption) (*UploadLogStatus_Response, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) UploadLogStream(ctx context.Context, opts ...grpc.CallOption) (Log_UploadLogStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Log_ServiceDesc.Streams[0], "/log.Log/UploadLogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &logUploadLogStreamClient{stream}
	return x, nil
}

type Log_UploadLogStreamClient interface {
	Send(*UploadLogStream_Request) error
	CloseAndRecv() (*UploadLogStream_Response, error)
	grpc.ClientStream
}

type logUploadLogStreamClient struct {
	grpc.ClientStream
}

func (x *logUploadLogStreamClient) Send(m *UploadLogStream_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logUploadLogStreamClient) CloseAndRecv() (*UploadLogStream_Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadLogStream_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logClient) UploadLogStatus(ctx context.Context, in *UploadLogStatus_Request, opts ...grpc.CallOption) (*UploadLogStatus_Response, error) {
	out := new(UploadLogStatus_Response)
	err := c.cc.Invoke(ctx, "/log.Log/UploadLogStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
// All implementations must embed UnimplementedLogServer
// for forward compatibility
type LogServer interface {
	UploadLogStream(Log_UploadLogStreamServer) error
	UploadLogStatus(context.Context, *UploadLogStatus_Request) (*UploadLogStatus_Response, error)
	mustEmbedUnimplementedLogServer()
}

// UnimplementedLogServer must be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (UnimplementedLogServer) UploadLogStream(Log_UploadLogStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadLogStream not implemented")
}
func (UnimplementedLogServer) UploadLogStatus(context.Context, *UploadLogStatus_Request) (*UploadLogStatus_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLogStatus not implemented")
}
func (UnimplementedLogServer) mustEmbedUnimplementedLogServer() {}

// UnsafeLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServer will
// result in compilation errors.
type UnsafeLogServer interface {
	mustEmbedUnimplementedLogServer()
}

func RegisterLogServer(s grpc.ServiceRegistrar, srv LogServer) {
	s.RegisterService(&Log_ServiceDesc, srv)
}

func _Log_UploadLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServer).UploadLogStream(&logUploadLogStreamServer{stream})
}

type Log_UploadLogStreamServer interface {
	SendAndClose(*UploadLogStream_Response) error
	Recv() (*UploadLogStream_Request, error)
	grpc.ServerStream
}

type logUploadLogStreamServer struct {
	grpc.ServerStream
}

func (x *logUploadLogStreamServer) SendAndClose(m *UploadLogStream_Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logUploadLogStreamServer) Recv() (*UploadLogStream_Request, error) {
	m := new(UploadLogStream_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Log_UploadLogStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLogStatus_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).UploadLogStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Log/UploadLogStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).UploadLogStatus(ctx, req.(*UploadLogStatus_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Log_ServiceDesc is the grpc.ServiceDesc for Log service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Log_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLogStatus",
			Handler:    _Log_UploadLogStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadLogStream",
			Handler:       _Log_UploadLogStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "log.proto",
}
